config/routes.rb
Rails.application.routes.draw do

  post  'likes/:article_id/create' => 'likes#create'
  delete 'likes/:article_id/destroy' => 'likes#destroy'

  post 'login' => 'users#login'
  get 'login' => 'users#login_form'
  post 'logout' => 'users#logout'
  get 'logout' => 'users#logout'

  get 'users/index' => 'users#index'
  get 'signup' => 'users#new'
  post 'users/create' => 'users#create'
  get 'users/:id' => 'users#show'
  post 'users/:id/update' => 'users#update'
  get 'users/:id/edit' => 'users#edit'



  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
  resources :comments
end
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :user_id, presence: true


    # def like_user?(user_id)
    # 	.include?(user_id)
    # end

  # scope :newer, -> { order(created_at: :desc) }
    def user
    	return User.find_by(id: self.user_id)
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
	validates :user_id, {presence: true}
	validates :article_id, {presence: true}
	belongs_to :user
	belongs_to :article

end

app/models/user.rb
class User < ApplicationRecord
	  has_secure_password
	  has_many :articles
	  has_many :likes, dependent: :destroy
	  validates :name, {presence: true}
	  validates :email, {presence: true, uniqueness: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user

	def set_current_user
		@current_user= User.find_by(id: session[:user_id])
	end

	def authenticate_user
	    if @current_user == nil
	      flash[:notice]="ログインが必要です"
	      redirect_to("/login")
	    end
  	end

  	def forbid_login_user
  		if @current_user
  			flash[:notice]="すでにログインしています"
  			redirect_to("/articles/")
  		end
  	end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
    before_action :authenticate_user, {only: [:index, :show, :edit, :update]}

    # before_action :set_user
    # before_action :forbid_login_user, {only: [:login_form, :login]}


	def show
		@article = Article.find(params[:id])
		@user = @article.user
	end

	def new
		@article = Article.new
	end

	def index
		@articles = Article.all.order(created_at: :desc).limit(10)
	end


	def create

		@article = Article.new(title: params[:title], text: params[:text], user_id: @current_user.id)

	    if @article.save
	       flash[:notice] = "記事の投稿が完了しました"
       	   redirect_to @article
        else
           render 'new'
        end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		 @article = Article.find(params[:id])

		 if @article.update(article_params)
		 	flash[:notice] = "記事を編集しました"
		    redirect_to @article
	     else
		    render 'edit'
		 end
	end

	def destroy
		 @article = Article.find(params[:id])
		 @article.destroy
		 flash[:notice] = "記事を削除しました"

	     redirect_to articles_path
	end

private
  	def article_params
    	params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

    private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 # before_action :check_like
 before_action :read_article

 # def create
 # 	@like=Like.new(user_id: @current_user.id, article_id: params[:article_id])
 # 	@like.save
 	# @articles.reload
 	# puts "!!!!!!!!!!!!!!!!!!!!!!" + request.path_info
 	# puts "??????????????????????" + '/articles/#{article_id}/create'
 # 	if request.path_info == '/articles/#{article_id}/create'
 # 		puts "一覧ページにいます"
 		# redirect_to("/articles")
 # 	else
 # 		puts "それ以外のページにいます"
 		# redirect_to("/articles/#{params[:article_id]}")
	# end
 # end

 def create
 	    @like=Like.new(user_id: @current_user.id, article_id: params[:article_id])
 		@like.save
 end


 def destroy
 	@like = Like.find_by(user_id: @current_user.id, article_id: params[:article_id])
    @like.destroy

    # @articles.reload
    # puts "!!!!!!!!!!!!!!!!!!!!!!1" + request.path_info
 #    if request.path_info == '/articles/#{@current_user.id}/create'
 #    	puts "一覧ページにいます"
 		# redirect_to("/articles")
 # 	else
 # 		puts "それ以外のページにいます"
 # 		redirect_to("/articles/#{params[:article_id]}")
	# end
 end

#  def create
#  	@article=Article.find_by(params[:article_id])
#  	@article.like_user(@current_user)
#  	redirect_to("/articles")
#  end

#  def destroy
#  	@article = Like.find(params[:id]).article
#     @article.unlike_user(@current_user)
#     redirect_to("/articles")
#  end

# private
#   	def check_like
#   		if Like.where(user_id: @current_user.id, article_id: params[:article_id])
#   			redirect_to action: :destroy
#   		else
#   			redirect_to action: :create

#   		end
#     end

   def read_article
   	  @article = Article.find_by(id: params[:article_id])
   end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  def index
    @users=User.all
    # render plain: params[:users].inspect
  end

  def show
    @user = User.find_by(id: params[:id])
    @articles = Article.where(user_id: params[:id]).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user= User.new(name: params[:name], email: params[:email], password: params[:password], image_name: params[:image])
    if params[:image]
      @user.image_name= "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/#{@user.image_name}",image.read )
    else
      @user.image_name= "no-image.png"
    end
    if @user.save
       session[:user_id] = @user.id
       flash[:notice] = "ユーザー登録が完了しました"
       redirect_to("/users/#{@user.id}")
    else
       render("users/new")
    end
  end

  def edit
    @user= User.find_by(id: params[:id])
  end

  def update
    @user= User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]

   if params[:image]
      @user.image_name= "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/#{@user.image_name}",image.read )
    end

    if @user.save
       flash[:notice] = "編集が完了しました"
       redirect_to("/users/#{@user.id}")
    else
       render("users/edit")
    end
  end

  def login_form
    @user=User.find_by(id: params[:id])
  end

  def login
    @user=User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      @error_message="メールアドレスまたはパスワードが間違っています"
      @email=params[:email]
      @password=params[:password]
      render("users/login_form")
    end

  end

  def logout
      session[:user_id] = nil
      flash[:notice] = "ログアウトしました"
      redirect_to("/login")
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to("/users/index")
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="text-center">
    <p class="mt-3">
      <%= form.label :タイトル %><br>
      <input class="form-control z-depth-1 col-xs-10 col-md-8 col-lg-7 mx-auto" name="title"></input>
    </p>

    <p class="mt-3">
      <%= form.label :本文 %><br>
      <textarea class="form-control z-depth-1 col-xs-10 col-md-8 col-lg-7 mx-auto" rows="3" placeholder="自由に書いてください" name="text"></textarea>
    </p>

    <div class="mx-auto text-center mt-4 mb-4">
      <%= form.submit :投稿, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="text-center container-sub pt-2 pb-3">
<h4 class="text-center">編集</h4>

<%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="text-center">
    <p class="mt-4">
      <%= form.label :タイトル %><br>
      <input class="form-control z-depth-1 col-xs-12 col-md-8 col-lg-7 mx-auto" name="title" value ="<%= @article.title %>"></input>
    </p>

    <p class="mt-5">
      <%= form.label :本文 %><br>
      <textarea class="form-control z-depth-1 col-xs-12 col-md-8 col-lg-7 mx-auto" rows="3" name="text"><%= @article.text %></textarea>
    </p>

    <div class="mx-auto text-center mt-4 mb-4">
      <%= form.submit :投稿, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>
	<div>
	<%= link_to '戻る', articles_path, class: "btn btn-secondary" %>
	</div>
</div>

app/views/articles/index.html.erb
<body>
  <div class="container-sub pb-2">
    <h4 class="text-center text-dark pt-3">投稿一覧</h4>

      <div>
      <table>
        <tr>
          <th class="text-dark text-center font-size-5"></th>
          <th class="text-dark text-center font-size-5"></th>
          <th colspan="1"></th>
        </tr>


      <% @articles.each do |article| %>
        <div>
          <tr class="border text-dark bg-white">
            <td>
              <%= link_to("users/#{article.user.id}") do %>

               <div class="display-block text-center mx-1">
                  <img src = "<%= "/#{article.user.image_name}" %>" class="user-image my-1">
                  <p><%= article.user.name%></p>
               </div>
               <% end %>
            </td>
            <td class="border-right w-75 pr-3">
                <p class="font-weight-bold mt-3"><%= link_to article.title, article_path(article) %></p>
                <p><%= article.text %></p>
                <p class="text-right mr-2"><%= time_ago_in_words(article.created_at) %> ago (<%= article.created_at.strftime('%Y/%m/%d %H:%M') %>)</p>
                <span class="float-right mb-3 mr-1">
                    <% if article.user == @current_user %>
                      <%= link_to '編集', edit_article_path(article), class: "btn btn-warning btn-sm text-right" %>
                      <%= link_to '削除', article_path(article),
                        method: :delete, data: { confirm: '本当に削除しますか?' } , class: "btn btn-secondary btn-sm  text-right"%>
                    <% end %>

                    <!-- コメントの数 -->
                      <span class="display-box py-2 px-1 text-center far fa-comments">(<%= Comment.where(article_id: article.id).count %>)</span>

                    <!-- いいね機能のview -->
                      <span class="display-box py-2 px-1 text-center">
                          <% if Like.find_by(user_id: @current_user.id, article_id: article.id) %>
                            <%= link_to("/likes/#{article.id}/destroy", method: :delete, remote: true) do %>
                              <span class="fas fa-heart liked-icon"  id="like-button<%= article.id %>"></span>
                            <% end %>
                          <% else %>
                            <%= link_to("/likes/#{article.id}/create", method: :post, remote: true) do %>
                              <span class="far fa-heart like-icon" id="like-button<%= article.id %>"></span>
                            <% end %>
                          <% end %>

                        <span id="like-count<%= article.id %>">(<%= Like.where(article_id: article.id).count %>)</span>
                     </span>
                     <!-- ここまでいいね機能 -->


                </span>
            </td>
          </tr>
        </div>
      <% end %>
      </table>
    </div>
  </div>
</body>

app/views/articles/new.html.erb
<body>
	<div class="container-sub text-center text-dark pt-2 pb-3">
		<h4 class="pt-3">新規投稿</h4>
		<div>
			<%= render 'form' %>
		</div>
		<div>
		<%= link_to '戻る', articles_path, class: "btn btn-secondary" %>
		<div>
	</div>
</body>

app/views/articles/show.html.erb
<div class="container-sub">
	<h2 class="text-center text-dark pt-3"><%= @article.created_at.strftime('%Y年%m月%d日 %H:%M') %>の投稿</h2>

		<p class="bg-light border mx-5">
		  <strong>タイトル:</strong>
		  「<%= @article.title %>」
		</p>

		<p class="bg-light border mx-5">
		  <strong>本文:</strong>
		  <%= @article.text %>
		</p>

		<h3 class="text-center mx-5 mt-5">コメント</h3>
		<%= render @article.comments %>
		<% if Like.find_by(user_id: @current_user.id, article_id: @article.id) %>
        	<%= link_to("/likes/#{@article.id}/destroy", {method: "post"}) do %>
        		<i class="fas fa-heart liked-icon"></i>
        	<% end %>
        <% else %>
        	<%= link_to("/likes/#{@article.id}/create", {method: "post"}) do %>
        		<span class="far fa-heart like-icon"></span>
        	<% end %>
        <% end %>


		<h3 class="text-center mx-5 mt-5">コメント追加</h3>
		<%= render "comments/form" %>
		<p class="text-center">
		<%= link_to '編集', edit_article_path(@article) %> |
		<%= link_to '記事一覧に戻る', articles_path %>
		</p>
</div>

app/views/comments/_comment.html.erb
<div class="mx-5 bg-light">
  	<div>
	  <strong>ユーザー:</strong>
	  <%= comment.commenter %>
	</div>
	<div>
	  <strong>コメント:</strong>
	  <%= comment.body %>
	</div>
</div>

<p class="text-center">
  <%= link_to 'コメントを削除', [comment.article, comment],
               method: :delete,
               data: { confirm: '本当に削除しますか?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p class="text-center">
    <%= form.label :ユーザー %><br>
    <%= form.text_field :commenter %>
  </p>
  <p class="text-center">
    <%= form.label :コメント %><br>
    <%= form.text_area :body %>
  </p>
  <p class="text-center">
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta  name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body class="px-3">
    <% if flash[:notice] %>
      <div class="alert alert-success text-center">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <nav class="navbar navbar-expand-sm navbar-light bg-white sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/"><img src="/logo2.png" id="logo"></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar" href="#Navbar">
            <span class="navbar-toggler-icon"></span>
          </button>
        <%if session[:user_id] %>
            <div class="collapse navbar-collapse" id="Navbar">
                  <ul class="navbar-nav ml-auto">
                      <li class="nav-item nav-link"><%= @current_user.name %></li>
                      <li class="nav-item nav-link"><%= link_to '投稿一覧', articles_path, class: 'text-dark' %></li>
                      <li class="nav-item nav-link"><%= link_to '新規投稿', new_article_path, class: 'text-dark'  %></li>
                      <li class="nav-item nav-link"><%= link_to 'ユーザー一覧', users_index_path, class: 'text-dark'  %></li>
                      <li class="nav-item nav-link"><%= link_to 'ログアウト', logout_path, class: 'text-dark'  %></li>
                  </ul>
            </div>
        <% else %>
            <div class="collapse navbar-collapse" id="menu">
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item nav-link"><%= link_to '新規登録', signup_path, class: 'text-dark'  %></li>
                    <li class="nav-item nav-link"><%= link_to 'ログイン', login_path, class: 'text-dark'  %></li>
                  </ul>
            </div>
        <% end %>

      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$(function(){
	alert('ライクしたよ');
	$('#like-count<%= @article.id %>').html("<%= Like.where(article_id: @article.id).count %>");
	$('#like-button<%= @article.id %>').removeClass('far like-icon').addClass('fas liked-icon');
});

app/views/likes/destroy.js.erb
$(function(){
	alert('ライク消したよ');
	$('#like-count<%= @article.id %>').html("<%= Like.where(article_id: @article.id).count %>");
	$('#like-button<%= @article.id %>').removeClass('fas liked-icon').addClass('far like-icon');
});

app/views/users/edit.html.erb
      <div>
      	<h4 class="pt-3">編集</h4>
      	<% @user.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>

	      	<%= form_tag("/users/#{@user.id}/update", {multipart: true}) do%>
		        <p>ユーザー名</p>
		        <!-- nameを初期値として表示-->
		        <input name = "name" value ="<%= @user.name %>">
		        <p>メールアドレス</p>
		        <!-- emailを初期値として表示 -->
		        <input name= "email" value ="<%= @user.email %>">
		        <p>画像</p>
		        <input name="image" type="file"><br>
		        <input type="submit" value="保存">
		    <% end %>
	    </div>
</div>

app/views/users/index.html.erb
  <div class="container-sub text-dark pt-2 pb-3">
    <h4 class="pt-3 text-center">ユーザー一覧</h4>
    <% @users.each do |user| %>
      <div class="col-xs-11 col-md-8 col-lg-7 mx-auto my-3 py-3 bg-white border">
        <img src = "<%= "/#{user.image_name}" %>" class="user-image mx-3">
      	<span class="pr-2 mr-2 border-right"><%= link_to(user.name, "/users/#{user.id}", class: "btn btn-light text-dark") %></span>
        <% if user.id == @current_user.id %>
      	<span><%= link_to("編集", "/users/#{user.id}/edit", class: "btn-sm btn-warning") %></span>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/users/login_form.html.erb
<div class="container-sub text-center text-dark">
  <h4 class="pt-3">ログイン</h4>
      <div>
        <% if @error_message %>
          <div class="text-danger">
            <%= @error_message %>
          </div>
        <% end %>
        <%= form_tag("/login") do %>
          <p class="mt-3">メールアドレス</p>
          <input name="email" value="<%= @email %>">
          <p class="mt-3">パスワード</p>
          <input type="password" name="password" value="<%= @password %>"><br>
          <input type="submit" value="ログイン" class="mt-3 btn btn-primary">
        <% end %>
       </div>
</div>

app/views/users/new.html.erb
      <div class="container-sub text-center text-dark bg-info">
        <h4 class="pt-3">新規ユーザー登録</h4>
      	<% @user.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>

      	<%= form_tag("/users/create", {multipart: true}) do %>
	        <p>ユーザー名</p>
	        <!-- <input>タグを用いて1行の入力フォーム -->
	        <input name="name" value="<%= @user.name %>">

	        <p>メールアドレス</p>
	        <!-- <input>タグを用いて1行の入力フォーム -->
	        <input name="email" value="<%= @user.email %>">

          <p>パスワード</p>
          <input type="password" name="password" value="<%= @user.password %>"><br>

          <p>画像</p>
          <input name="image" type="file"><br>

	        <input type="submit" value="新規登録" class="mt-3 btn btn-primary">
	    <% end %>
      </div>

app/views/users/show.html.erb
 <div class="col-xs-12 col-md-12 col-lg-11">
 	<div class="text-center user-info border">
 		<div class="my-3">
		 	 <img src = "<%= "/#{@user.image_name}" %>" class="user-image-lg">
		</div>
		<div>
		      <!-- 以下で、ユーザー名を出力-->
		      <h2><%= @user.name %></h2>
		      <!-- 以下で、メールアドレスを出力-->
		      <p><%= @user.email %></p>
		      <span>
		      <% if @user == @current_user %>
		      <%= link_to("編集", "/users/#{@user.id}/edit", class: "btn btn-warning btn-md text-right mb-2") %>
		      <% end %>
		      </span>
 		 </div>
 		</div>
 		<div class="text-center">
 		 <%= link_to("ユーザー一覧へ", "/users/index", class: "btn btn-secondary btn-md text-right my-3")%>
    	</div>


      <h4 class="text-center mt-3">このユーザーの投稿一覧 </h4>
       <table class="m-3 mx-auto">
        <tr>
          <th class="text-dark text-center font-size-5"></th>
          <th class="text-dark text-center font-size-5"></th>
          <th colspan="1"></th>
        </tr>

      	<% @articles.each do |article| %>
        <div>
          <tr class="border text-dark bg-light">
            <td>
               <div class="display-block text-center mx-1">
                  <img src = "<%= "/#{article.user.image_name}" %>" class="user-image my-1">
                  <p><%= article.user.name%></p>
               </div>
            </td>
            <td class="border-right w-75">
                <p class="font-weight-bold"><%= link_to article.title, article_path(article) %></p>
                <p><%= article.text %></p>
                <p class="text-right mr-2"><%= time_ago_in_words(article.created_at) %> ago (<%= article.created_at.strftime('%Y/%m/%d %H:%M') %>)</p>
                <span class="float-right mb-1 mr-1">
                    <% if article.user == @current_user %>
                      <%= link_to '編集', edit_article_path(article), class: "btn btn-warning btn-sm text-right" %>
                      <%= link_to '削除', article_path(article),
                        method: :delete, data: { confirm: '本当に削除しますか?' } , class: "btn btn-secondary btn-sm  text-right"%>
                    <% end %>
                    <!-- コメントの数 -->
                     <span>
                     	<i class="far fa-comments">ああああ</i>
                        <text>aaaa</text>
                     </span>

                    <!-- いいね機能のview -->
                      <span class="display-box py-2 px-1 text-center">
                          <% if Like.find_by(user_id: @current_user.id, article_id: article.id) %>
                            <%= link_to("/likes/#{article.id}/destroy", method: :delete, remote: true) do %>
                              <i class="fas fa-heart liked-icon"  id="like-button<%= article.id %>"></i>
                            <% end %>
                          <% else %>
                            <%= link_to("/likes/#{article.id}/create", method: :post, remote: true) do %>
                              <span class="far fa-heart like-icon" id="like-button<%= article.id %>"></span>
                            <% end %>
                          <% end %>

                        <span id="like-count<%= article.id %>"><%= Like.where(article_id: article.id).count %></span>
                     </span>
                     <!-- ここまでいいね機能 -->


                </span>
            </td>
          </tr>
        </div>
      <% end %>
 	 </table>
 	  <div class="text-center">
 	 	<%= link_to("ユーザー一覧へ", "/users/index", class: "btn btn-secondary btn-md text-right my-3")%>
 	  </div>
      </div>

app/views/welcome/index.html.erb
<div class="text-center col-xs-12 col-md-12 col-lg-12 container m-0 p-0">
	<h1 class="text-center text-light font-weight-bold shadow-sm display-3 pt-4 display-block mb-5">Share your own story!</h1>

	<%if session[:user_id]== nil %>
		<%= link_to("/login") do %>
			<div>
				<button class="display-block d-sm-none btn-lg btn-success mt-5 mb-2">ログイン</button>
			</div>
		<% end %>
		<%= link_to("/signup") do %>
		<div>
			<button class="display-block d-sm-none btn-lg btn-primary mt-2">新規登録</button>
		</div>
		<% end %>
	<% end %>
</div>
<p class="text-center">©Hiroki Anzai</p>